INSERT INTO PUBLIC.DOSSIER_BATCH_JOB (UUID, JOB_TYPE, PRIORITY, CREATE_TIMESTAMP, DESCRIPTION, STATUS, RESULT)
VALUES
  ('10000001', 'BTCHANNSTATPROTO', 1, CURRENT_TIMESTAMP, 'a simple psob task', 'NEW', ''),
  ('10000002', 'BTCHANNSTATPROTO', 1, CURRENT_TIMESTAMP, 'a simple psob task number two', 'NEW', ''),
  ('10000003', 'BTCHANNSTATPROTO', 1, CURRENT_TIMESTAMP, 'a simple PENDING psob task', 'PND', ''),
  ('10000004', 'BTCHANNSTATPROTO', 1, CURRENT_TIMESTAMP, 'a simple PENDING psob task', 'PND', ''),
  ('10000005', 'BTCHANNSTATPROTO', 1, CURRENT_TIMESTAMP, 'a simple PENDING psob task', 'PND', ''),
  ('10000006', 'BTCHANNSTATPROTO', 1, CURRENT_TIMESTAMP, 'a simple PENDING psob task', 'PND', ''),
  ('10000007', 'ANOTHERTYPE', 1, CURRENT_TIMESTAMP, 'a simple PENDING psob task', 'PND', '');


INSERT INTO PUBLIC.DOSSIER_BATCH_PARAM (JOB_ID, PARAM_KEY, PARAM_VAL)
VALUES
  (1, 'IRN', '123456789'),
  (1, 'OWNER', 'psob admin'),
  (2, 'IRN', '987654321');